LANDING_PAGE/urls.py
from django.conf.urls import url
from .views import index
from .views import add_activity
from .views import profile
from .views import data_json
from .views import book
from .views import registration
from .views import validasi
from .views import success
# from .views import mydiarylist
# from .views import mydiary
from django.urls import re_path

urlpatterns = [
 re_path(r'^$', index, name='index'),
 re_path('profile-page/' , profile, name='profile'),
 re_path('add_activity/', add_activity, name='add_activity'),
 re_path('book_data_json/' , data_json, name='data_json'),
 re_path('book_list', book, name='book'),
 re_path('registration', registration, name="registration"),
 re_path('validasi', validasi, name="validasi"),
 re_path('success', success, name="success"),

#  re_path('apippw/mydiary/new', mydiary,name='mydiary'),
#  re_path('apippw/mydiary/list', mydiarylist,name='mydiarylist')
]

NEW_WEBSITE_6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from LANDING_PAGE.views import home
# import LANDING_PAGE.urls as LANDING_PAGE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('landing-page/', include(('LANDING_PAGE.urls', 'LANDING_PAGE'), namespace = 'LANDING_PAGE')),
    path('profile-page/', include(('LANDING_PAGE.urls', 'LANDING_PAGE'), namespace = 'profile_page')),
    # url(r'^login/$', auth_views.login, name='login'),
    path('login/',auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name="login.html"), name="logout"),
    # path(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^$', home, name='home'),
    
]

LANDING_PAGE/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Diary(models.Model):
    date = models.DateTimeField(default = datetime.now())
    activity = models.TextField(max_length=60)

class Registration(models.Model):
	nama = models.CharField(max_length = 50)
	password = models.CharField(max_length = 20)
	email = models.CharField(max_length = 50)


# Create your models here.

LANDING_PAGE/forms.py
from django import forms
class form_Diary(forms.Form):
    diary = forms.CharField(widget = forms.Textarea(),max_length = 300,required = True)

class form_Registration(forms.Form):
	email_attrs = {
		'type': 'text',
		'class': 'form-control',
		'placeholder':'Example: aaaaa@gmail.com',
	}
	nama_attrs = {
		'type': 'text',
		'class': 'form-control',
		'placeholder':'Full Name',
	}
	password_attrs = {
		'type': 'password',
		'class': 'form-control',
		'placeholder':'Password',
	}
	nama = forms.CharField(max_length = 50, error_messages={"required": "Mohon masukkan nama Anda"}, widget = forms.TextInput(attrs=nama_attrs))
	password = forms.CharField(max_length = 20, min_length=8, widget = forms.PasswordInput(attrs=password_attrs), error_messages={"min_length": "password harus lebih dari atau sama dengan 8 karakter"})
	email = forms.EmailField(error_messages={"required": "Mohon masukkan email yang valid"}, max_length=50, widget=forms.TextInput(attrs=email_attrs))

LANDING_PAGE/views.py
from django.shortcuts import render,redirect
from .models import Diary, Registration
from .forms import form_Diary, form_Registration
from . import forms
from datetime import datetime
from django.http import HttpResponseRedirect , JsonResponse
import pytz
import json
import requests
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login

# Create your views here.
response = {}

def home(request):
	return render(request, 'home.html')
	
def index(request):
    response['form'] = forms.form_Diary
    response['diary'] = Diary.objects.all()
    html = 'new_Website.html'
    return render(request, html, response)

def profile(request):
    return render(request, 'profile_tdd.html')

def book(request): #render html buku baru
    return render(request, 'book.html')

def data_json(request):
    list_buku = requests.get("https://www.googleapis.com/books/v1/volumes?q=quilting")
    json_buku = list_buku.json()
    return JsonResponse(json_buku)

def add_activity(request):
    form = forms.form_Diary(request.POST)
    if form.is_valid():
        response['diary'] = request.POST['diary']
        diary = Diary(activity = response['diary'])
        diary.save()
        return HttpResponseRedirect('/landing-page/')
    else:
        form = forms.form_Diary()
    
    return render(request, 'new_Website.html', response)

def registration(request):
	response = {}
	response["forms"] = form_Registration
	return render(request, 'registration.html', response)

@csrf_exempt
def validasi(request):
	email = request.POST.get("email")
	data = {'not_valid': Subscribers.objects.filter(email__iexact=email).exists()}
	return JsonResponse(data)

def success(request):
	submited_form = form_Registration(request.POST or None)
	if (submited_form.is_valid()):
		cd = submited_form.cleaned_data
		new_subscriber = Registration(name=cd['nama'], password=cd['password'], email=cd['email'])
		new_subscriber.save()
		data = {'nama': cd['nama'], 'password': cd['password'], 'email': cd['email']}
	return JsonResponse(data)

def my_view(request):
	username = request.POST['username']
	password = request.POST['password']
	user = authenticate(request, username=username,password=password)
	if user is not None:
		requeest.session['user_login'] = username
		messages.success(request)

LANDING_PAGE/templates/book.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <link rel = "stylesheet" type = "text/css" href= "{% static 'css/story_8.css' %}"/>
    <script type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/story_8.js' %}"></script>
</head>
<body style="background-color:aqua">
    <h1> KATALOG BUKU</h1>
    <h2 id= "jumlah_buku_favorit" style = "text-align: center">
        <i class='fa fa-star'style = 'color : yellow'> </i> 
    </h2>
    <table class = "table-responsive table table-hover table table-stripped" id="tabel_list_buku"></table>
</body>
</html>

LANDING_PAGE/templates/home.html
{% block content %}
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.username }}</p>
	{% else %}
             <a class="lead" href="{% url 'login' %}">Log in</a>
    {% endif %}
    <button type="button" class="btn btn-info" onclick="window.location.href='/landing-page'"> SIGN OUT </button>
{% endblock content %}

LANDING_PAGE/templates/login.html
{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
   <br>
  <p><strong>-- OR --</strong></p>
  <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
{% endblock %}

LANDING_PAGE/templates/new_Website.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <link rel = "stylesheet" type = "text/css" href= "{% static 'css/story_8.css' %}"/>
    <script type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/story_8.js' %}"></script>
</head>
<!-- <div id="load">
    <img src="{% static 'loading.gif' %}">
</div> -->
<body style="background-color:aqua">
  <!-- <div class="loader"></div> -->
  <h1 align="center">Hello, Apa kabar?</h1>
  <button id=buttonUbahTema style="margin:0 0 5px 0"> Ubah tema </button>
  <button id=buttonTemaAwal style="margin:0 5px 5px 0"> Tema Awal </button>
  <button type="button" class="btn btn-info" onclick="window.location.href='/landing-page/book_list'"> LAB_9,BOOK LIST </button>
  <button type="button" class="btn btn-info" onclick="window.location.href='/login'"> SIGN IN </button>

  <div>
    <button class="accordion" id="accordionSatu" style="margin:0 0 3px 0">Aktivitas</button>
    <div class="panel" id="panel1" style="margin:0 0 3px 0">
            <p>Saya sedang menonton theater <br>
                Saya sedang di kereta <br>
                Saya sedang menaiki busway <br>
                Saya sedang berlari</p>
    </div>
  </div>

  <button class="accordion" id="accordionDua" style="margin:0 0 3px 0">Kepanitiaan/Organisasi</button>
  <div class="panel" id="panel2" style="margin:0 0 3px 0">
        <p>Staff Penunjang CGT 25 <br>
            Staff DharmaWidya HFG 12 <br>
        </p>
  </div>

  <button class="accordion" id="accordionTiga" style="margin:0 0 3px 0">Organisasi</button>
  <div class="panel" id="panel3" style="margin:0 0 5px 0">
        <p>Staff Departemen Olahraga BEM FASILKOM UI 2018 <br>
            Staff Divisi Olahraga KMHD UI 2018
        </p>
  </div>
  <form id="form" method = "POST" action = "{% url 'LANDING_PAGE:add_activity' %}">
    {% csrf_token %}
    {{form}}
    <input id="submit" type="submit" class = "btn btn-lg btn block btn-info" style="background-color:khaki" value="Submit">

  </form>

  <div class="table-responsive" style="background-color:lightcoral">
      {% if diary %}
      <table class = "table table-hover">
          <thead>
              <th> Date </th>
              <th> Status </th>
          </thead>
          {% for data in diary %}
          <tr>
          <td> {{ data.date }} </td>
          <td> {{ data.activity }} </td>
          </tr>
          {% endfor %}
      </table>
      {% else %}
      <h2> No Status </h2>
      {% endif %}
  </div>

  <p>My first paragraph.</p>

</body>
<!-- <style>
.temaBackground2{
    background-color:pink !important;
}
.temaTombol2{
    background-color:greenyellow !important;
}
.table-responsive2{
    background-color: powderblue !important;
}
/* Style the buttons that are used to open and close the accordion panel */
.accordion {
    background-color:khaki;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    text-align: left;
    border: none;
    outline: none;
    transition: 0.4s;
}

/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
/* .active, .accordion:hover {
    background-color: paleturquoise;
}

.active2, .accordion:hover {
    background-color: red;
} */


/* Style the accordion panel. Note: hidden by default */
.panel {
    padding: 0 18px;
    background-color: white;
    display: none;
    overflow: hidden;
}
</style> -->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
<!-- <script type="text/javascript">
$(document).ready(function(){
    $("#buttonUbahTema").click(function(){
        $("body").addClass("temaBackground2");
        $(".btn").addClass("temaTombol2");
        $(".accordion").addClass("temaTombol2")
        $(".table-responsive").addClass("table-responsive2")
    });
    $("#buttonTemaAwal").click(function(){
        $("body").removeClass("temaBackground2");
        $(".btn").removeClass("temaTombol2");
        $(".accordion").removeClass("temaTombol2")
        $(".table-responsive").removeClass("table-responsive2")

    });
    $("#accordionSatu").click(function(){
        $("#panel1").slideToggle("slow");
    });
    $("#accordionDua").click(function(){
        $("#panel2").slideToggle("slow");
    });
    $("#accordionTiga").click(function(){
        $("#panel3").slideToggle("slow");
    });
});
</script> -->
<!-- <script type="text/javascript" src="story_8.js"></script> -->
</html>

LANDING_PAGE/templates/registration.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <link rel = "stylesheet" type = "text/css" href= "{% static 'css/story_8.css' %}"/>
    <script type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/story_8.js' %}"></script>
</head>
<body style="background-color:aqua">
    <h1 align="center">SUBSCRIBE ME PLEASE :)</h1>
    <form id="form" method = "POST">
        {% csrf_token %}
        <div class ="container">
            <div class="row m-5">
                <div class="col-md-4"></div>
                <div class="col-md-4" id="subscribepage">
                    <div class="form-group">
                        {{ forms }}
                    </div>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
        <input id="submit_subscribe" type="submit" class = "btn btn-lg btn block btn-info" style="background-color:khaki" value="Submit">
    </form>
</body>